In [8]:
import numpy as np

A = np.array([[56.0, 0.0, 4.0, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print (A)

[[ 56.    0.    4.   68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [9]:
#Add things along the column aixs
calories = A.sum(axis=0)
print (calories)

[ 59.  239.  155.   76.9]


In [10]:
# Does a row wise division
percentage = 100 * A/calories
print(percentage)

[[94.91525424  0.          2.58064516 88.42652796]
 [ 2.03389831 43.51464435 33.5483871  10.40312094]
 [ 3.05084746 56.48535565 63.87096774  1.17035111]]
